SETTINGS_FIELD = "Settings"

AI_FIELD = "AI"
AO_FIELD = "AO"
DAQ_FIELD = "DAQ"
SCAN_FIELD = "Scan"

INTERFACE_TYPE_FIELD = "InterfaceType"
CONNECTION_CODE_FIELD = "ConnectionCode"

SAMPLE_RATE_FIELD = "SampleRate"
CHANNEL_COUNT_FIELD = "ChannelCount"
OPTIONS_FIELD = "Options"

RANGE_ID_FIELD = "RangeId"
LOW_CHANNEL_FIELD = "LowChannel"
HIGH_CHANNEL_FIELD = "HighChannel"
INPUT_MODE_FIELD = "InputMode"
SCAN_FLAGS_FIELD = "ScanFlags"
